spool "C:/Users/itiwari/Desktop/Project/Table3.txt"
CREATE TABLE LOGX11 ( id INT PRIMARY KEY, name VARCHAR(20) );
INSERT INTO LOGX11 VALUES ( 11, 'Alpha' );
INSERT INTO LOGX11 VALUES ( 22, 'Beta' );
INSERT INTO LOGX11 VALUES ( 33, 'Charlie' );
INSERT INTO LOGX11 VALUES ( 44, 'Darson' );
INSERT INTO LOGX11 VALUES ( 55, 'Eddy' );
INSERT INTO LOGX11 VALUES ( 66, 'Finch' );
INSERT INTO LOGX11 VALUES ( 77, 'Garry' );
INSERT INTO LOGX11 VALUES ( 88, 'Harry' );
INSERT INTO LOGX11 VALUES ( 99, 'Irwin' );
INSERT INTO LOGX11 VALUES ( 129, 'Junkie' );
INSERT INTO LOGX11 VALUES ( 199, 'Kevin' );
INSERT INTO LOGX11 VALUES ( 239, 'Liam' );
INSERT INTO LOGX11 VALUES ( 249, 'Martin' );
spool off;
